fastlane_version "2.27.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test_travis do
    scan(scheme: "WeDeploy", clean: true, skip_testing: ['Tests/WeDeployAuthTest', 'Tests/WeDeployDataTest', 'Tests/WeDeployDataCreationTest', 'Tests/WeDeployEmailTest'])
    scan(scheme: "WeDeploy-macOS", clean: true, destination: 'platform=macOS', skip_testing: ['WeDeploy-macOSTests/WeDeployAuthTest', 'WeDeploy-macOSTests/WeDeployDataTest', 'WeDeploy-macOSTests/WeDeployDataCreationTest', 'WeDeploy-macOSTests/WeDeployEmailTest'])
    scan(scheme: "WeDeploy-tvOS", clean: true, skip_testing: ['WeDeploy-tvOSTests/WeDeployAuthTest', 'WeDeploy-tvOSTests/WeDeployDataTest', 'WeDeploy-tvOSTests/WeDeployDataCreationTest', 'WeDeploy-tvOSTests/WeDeployEmailTest'])
  end

  lane :test_all_schemes do
    scan(scheme: "WeDeploy", clean: true)
    scan(scheme: "WeDeploy-macOS", clean: true)
    scan(scheme: "WeDeploy-tvOS", clean: true)
  end

  lane :pod_lib_lint do
    pod_lib_lint(verbose: true)
  end

end